### ISSUE TITLE
请问 noopener noreferrer是为了解决钓鱼漏洞吗

### ISSUE THREAD

**Issue by AlliotTech** [liuzc/hexo-autonofollow#2]
你好，发现插件添加的为nofollow noopener noreferrer， 这样导致站长工具的友链nofollow检测工具失效。

**Comment by liuzc** [comment]
请参考这篇文章：[https://my.oschina.net/jsan/blog/741317](https://my.oschina.net/jsan/blog/741317)

另外，如果你不想过滤友链，可以参考Readme进行配置：[https://github.com/liuzc/hexo-autonofollow#options](https://github.com/liuzc/hexo-autonofollow#options)
